/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List products
 */
export const ListProductsResponseItem = zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "category": zod.string(),
  "price": zod.number(),
  "quantity": zod.number().int(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})
export const ListProductsResponse = zod.array(ListProductsResponseItem)


/**
 * @summary Create a product
 */


export const createProductBodyPriceMin = 0;

export const createProductBodyQuantityMin = 0;



export const CreateProductBody = zod.object({
  "name": zod.string().min(1),
  "category": zod.string().min(1),
  "price": zod.number().min(createProductBodyPriceMin),
  "quantity": zod.number().int().min(createProductBodyQuantityMin)
})

export const CreateProductResponse = zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "category": zod.string(),
  "price": zod.number(),
  "quantity": zod.number().int(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Update a product
 */



export const UpdateProductParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})



export const updateProductBodyOnePriceMin = 0;

export const updateProductBodyOneQuantityMin = 0;



export const UpdateProductBody = zod.object({
  "name": zod.string().min(1),
  "category": zod.string().min(1),
  "price": zod.number().min(updateProductBodyOnePriceMin),
  "quantity": zod.number().int().min(updateProductBodyOneQuantityMin)
})

export const UpdateProductResponse = zod.object({
  "id": zod.number().int(),
  "name": zod.string(),
  "category": zod.string(),
  "price": zod.number(),
  "quantity": zod.number().int(),
  "createdAt": zod.coerce.date(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Delete a product
 */



export const DeleteProductParams = zod.object({
  "id": zod.coerce.number().int().min(1)
})

export const DeleteProductResponse = zod.void()


/**
 * @summary Get store settings
 */
export const getSettingsResponseLowStockThresholdMin = 0;



export const GetSettingsResponse = zod.object({
  "id": zod.number().int(),
  "businessName": zod.string(),
  "currency": zod.string().min(3).max(3),
  "lowStockThreshold": zod.number().int().min(getSettingsResponseLowStockThresholdMin),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Update store settings
 */

export const updateSettingsBodyLowStockThresholdMin = 0;



export const UpdateSettingsBody = zod.object({
  "businessName": zod.string().min(1),
  "currency": zod.string().min(3).max(3),
  "lowStockThreshold": zod.number().int().min(updateSettingsBodyLowStockThresholdMin)
})

export const updateSettingsResponseLowStockThresholdMin = 0;



export const UpdateSettingsResponse = zod.object({
  "id": zod.number().int(),
  "businessName": zod.string(),
  "currency": zod.string().min(3).max(3),
  "lowStockThreshold": zod.number().int().min(updateSettingsResponseLowStockThresholdMin),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary List stock movements
 */
export const ListStockMovementsResponseItem = zod.object({
  "id": zod.number().int(),
  "productId": zod.number().int(),
  "type": zod.enum(['add', 'remove']),
  "quantity": zod.number().int(),
  "createdAt": zod.coerce.date()
})
export const ListStockMovementsResponse = zod.array(ListStockMovementsResponseItem)


/**
 * @summary Create a stock movement
 */




export const CreateStockMovementBody = zod.object({
  "productId": zod.number().int().min(1),
  "type": zod.enum(['add', 'remove']),
  "quantity": zod.number().int().min(1)
})

export const CreateStockMovementResponse = zod.object({
  "id": zod.number().int(),
  "productId": zod.number().int(),
  "type": zod.enum(['add', 'remove']),
  "quantity": zod.number().int(),
  "createdAt": zod.coerce.date()
})


