/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Error {
  error: string;
}

export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  quantity: number;
  createdAt: string;
  updatedAt: string;
}

export interface ProductInput {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  category: string;
  /** @minimum 0 */
  price: number;
  /** @minimum 0 */
  quantity: number;
}

export type ProductUpdate = ProductInput;

export interface Settings {
  id: number;
  businessName: string;
  currency: string;
  /** @minimum 0 */
  lowStockThreshold: number;
  updatedAt: string;
}

export interface SettingsInput {
  /** @minLength 1 */
  businessName: string;
  /** @minLength 3 @maxLength 3 */
  currency: string;
  /** @minimum 0 */
  lowStockThreshold: number;
}

export type StockMovementType = typeof StockMovementType[keyof typeof StockMovementType];


export const StockMovementType = {
  add: 'add',
  remove: 'remove',
} as const;

export interface StockMovement {
  id: number;
  productId: number;
  type: StockMovementType;
  quantity: number;
  createdAt: string;
}

export type StockMovementInputType = typeof StockMovementInputType[keyof typeof StockMovementInputType];


export const StockMovementInputType = {
  add: 'add',
  remove: 'remove',
} as const;

export interface StockMovementInput {
  /** @minimum 1 */
  productId: number;
  type: StockMovementInputType;
  /** @minimum 1 */
  quantity: number;
}

