/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */
import type { ProductInput } from './productInput';

export type ProductUpdate = ProductInput;
