/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */

export interface Settings {
  id: number;
  businessName: string;
  currency: string;
  /** @minimum 0 */
  lowStockThreshold: number;
  updatedAt: Date;
}
