/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */

export type StockMovementInputType = typeof StockMovementInputType[keyof typeof StockMovementInputType];


export const StockMovementInputType = {
  add: 'add',
  remove: 'remove',
} as const;
