/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementType } from './stockMovementType';

export interface StockMovement {
  id: number;
  productId: number;
  type: StockMovementType;
  quantity: number;
  createdAt: Date;
}
