/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */
import type { StockMovementInputType } from './stockMovementInputType';

export interface StockMovementInput {
  /** @minimum 1 */
  productId: number;
  type: StockMovementInputType;
  /** @minimum 1 */
  quantity: number;
}
