/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * MAXY Media inventory API
 * OpenAPI spec version: 0.1.0
 */

export type StockMovementType = typeof StockMovementType[keyof typeof StockMovementType];


export const StockMovementType = {
  add: 'add',
  remove: 'remove',
} as const;
